from RAG_PIPELINE.src.graph import app_graph
from typing import Optional

async def perform_rag_search(query: str) -> str:
    """
    Search connected documents for answers using the RAG pipeline.
    
    Args:
        query: The user's question about the documents (e.g., "Summarize the invoice").
        
    Returns:
        The text answer generated by the document analysis system.
    """
    try:
        # Invoke the LangGraph pipeline
        # The graph expects {"question": ...} and returns a state dict
        result = await app_graph.ainvoke({"question": query})
        
        # Extract the generation
        answer = result.get("generation")
        if not answer:
            return "Analysis complete, but no direct answer was generated."
            
        return answer
    except Exception as e:
        return f"Error performing RAG search: {str(e)}"
