from RAG_PIPELINE.src.graph import app_graph
from typing import Optional

async def perform_rag_search(query: str) -> str:
    """
    Search connected documents for answers using the RAG pipeline.
    
    Args:
        query: The user's question about the documents (e.g., "Summarize the invoice").
        
    Returns:
        The text answer generated by the document analysis system.
    """
    try:
        # Invoke the LangGraph pipeline
        # The graph expects {"question": ...} and returns a state dict
        result = await app_graph.ainvoke({"question": query})
        
        # Extract the generation
        answer = result.get("generation")
        if not answer:
            return "Analysis complete, but no direct answer was generated."
            
        return answer
    except Exception as e:
        return f"Error performing RAG search: {str(e)}"


async def ask_stock_analyst(query: str) -> str:
    """
    Delegate a stock analysis question to the Stock Analysis Multi-Agent System.
    Use this for any question about stock prices, market trends, portfolio optimization,
    or investment recommendations for specific tickers (e.g., AAPL, TSLA, NVDA).
    
    Args:
        query: The user's question about stocks or market analysis.
        
    Returns:
        A comprehensive analysis and recommendation from the stock analysis team.
    """
    try:
        from StockAgents.backend.services.agent_engine import agent_engine
        
        # Run the multi-agent workflow
        result = await agent_engine.run_workflow(query, user_context={})
        
        # Return the synthesized recommendation
        return result.get("recommendation", "Stock analysis completed, but no recommendation was generated.")
    except Exception as e:
        return f"Error performing stock analysis: {str(e)}"

